version: "2.2"

x-common: &common
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "5"

services:
  mongo:
    image: mongo
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - ${MH_DUMP_DIR}:/dump
      - ${MH_DATA_DIR}/mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping")' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 3s
      retries: 5
    <<: *common

  web:
    build:
      context: ../web
      dockerfile: ../docker/web.dockerfile
    ports:
      - "${MH_PORT}:80"
    volumes:
      - ./mh.caddyfile:/etc/caddy/Caddyfile
    <<: *common

  mh:
    build:
      context: ../
      dockerfile: ./docker/mh.dockerfile
    <<: *common
    depends_on:
      - mongo


  